[variables]
# Python version
PYTHON_VERSION = "3.11"

[phases.build]
# Install minimal system dependencies
aptPkgs = ["libmagic1", "curl"]

[start]
# Optimized start command for Railway
cmd = "python test-app.py"