[variables]
# Python version
PYTHON_VERSION = "3.11"

[phases.build]
# Install minimal system dependencies
aptPkgs = ["libmagic1", "curl"]

[start]
# Optimized start command for Railway
cmd = "gunicorn backend.app:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 120"