[variables]
# Python version and environment
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_CACHE = "true"

[phases.build]
# Install system dependencies
aptPkgs = ["libmagic1", "libffi-dev", "curl", "ca-certificates"]

[phases.install]
# Install Python dependencies
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements_multimodal.txt",
    "pip install gunicorn==21.2.0 uvloop==0.19.0 httptools==0.6.1"
]

[start]
# Start command for Railway
cmd = "gunicorn backend.app:app -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 300"