[variables]
# Python version and environment  
PYTHON_VERSION = "3.11"

[phases.build]
# Install minimal system dependencies
aptPkgs = ["libmagic1", "curl"]

[phases.install]
# Install Python dependencies efficiently
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements_multimodal.txt",
    "pip install --no-cache-dir gunicorn==21.2.0"
]

[start]
# Optimized start command for Railway
cmd = "gunicorn backend.app:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 120"