[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
startCommand = "python test-app.py"

[env]
LOGODETH_ENVIRONMENT = "production"
LOGODETH_WORKER_COUNT = "1"
LOGODETH_CACHE_TTL = "172800"
LOGODETH_API_RATE_LIMIT = "30"
LOGODETH_MAX_FILE_SIZE = "10485760"
# OpenRouter integration for cost-effective AI
LOGODETH_USE_OPENROUTER = "true"
LOGODETH_OPENAI_MODEL = "google/gemini-pro-vision"  # Cost-effective vision model